version: '2.1'

services:

  base-app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/code
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U base-app"]
      interval: 2s
      retries: 10
    command: npm start

  # This proxy dependency is a workaround due to depends_on conditions not being
  # honoured when `docker-compose run` is used.
  # see https://github.com/docker/compose/issues/4369#issuecomment-274924088
  proxy_dep:
    image: "backstopjs/backstopjs:3.8.8"
    depends_on:
      base-app:
        condition: service_healthy

  backstop:
    image: "backstopjs/backstopjs"

    volumes:
      - ./:/src
    depends_on:
      - proxy_dep
