# base image
FROM cypress/browsers:chrome65-ff57

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# install cypress
RUN npm install cypress

# confirm the cypress install
RUN ./node_modules/.bin/cypress verify
