name: Create alpha package

on:
  push:
    tags:
      - '*-alpha.*'

jobs:
  build:
    name: Create alpha package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install
      
      - name: Run linting
        run: npm run lint
    
      - name: Run tests
        run: npm test

      - name: Build release artifact
        run: npm run build-gh-release

      - name: Publish NPM package
        run: npm publish --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
